const js = require('@eslint/js');
const globals = require('globals');
const stylistic = require('@stylistic/eslint-plugin');

module.exports = [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: { ...globals.node, VERSION: 'readonly', LICENSE: 'readonly' },
    },
    // Preserve legacy (.eslintrc) behavior: unused eslint-disable directives
    // were not reported unless explicitly requested, and the lint script does
    // not pass --report-unused-disable-directives.
    linterOptions: {
      reportUnusedDisableDirectives: 'off',
    },
    plugins: { '@stylistic': stylistic },
    rules: {
      // no-useless-assignment was added to eslint:recommended after ESLint 8;
      // it was not active under the legacy config, so keep it off.
      'no-useless-assignment': 0,
      // --- Stylistic / formatting rules (moved to @stylistic) ---
      '@stylistic/comma-dangle': [1, 'always-multiline'],
      '@stylistic/no-extra-parens': [1, 'all'],
      '@stylistic/no-extra-semi': 2,
      '@stylistic/dot-location': [2, 'property'],
      '@stylistic/no-floating-decimal': 1,
      '@stylistic/no-multi-spaces': 1,
      '@stylistic/array-bracket-spacing': [1, 'never', {}],
      '@stylistic/brace-style': [2, '1tbs', {}],
      '@stylistic/comma-spacing': 1,
      '@stylistic/comma-style': 1,
      '@stylistic/eol-last': 2,
      '@stylistic/indent': [1, 2, { SwitchCase: 1 }],
      '@stylistic/key-spacing': [2, { afterColon: true }],
      '@stylistic/linebreak-style': [1, 'unix'],
      '@stylistic/new-parens': 1,
      '@stylistic/no-mixed-spaces-and-tabs': [2],
      '@stylistic/no-multiple-empty-lines': [1, { max: 2 }],
      // no-spaced-func is a deprecated alias of function-call-spacing
      '@stylistic/function-call-spacing': 2,
      '@stylistic/no-trailing-spaces': [1, { skipBlankLines: false }],
      '@stylistic/quotes': [1, 'single', { avoidEscape: true }],
      '@stylistic/semi': [2, 'always'],
      '@stylistic/space-before-blocks': [2, 'always'],
      '@stylistic/space-in-parens': [1, 'never'],
      '@stylistic/space-infix-ops': [1, { int32Hint: true }],
      '@stylistic/space-unary-ops': [2, { words: true, nonwords: false }],
      '@stylistic/spaced-comment': [2, 'always', {}],
      '@stylistic/keyword-spacing': [1, { after: true }],

      // --- Core rules (correctness / best practices) ---
      'no-cond-assign': [1, 'always'],
      'no-console': [1, { allow: ['warn', 'error'] }],
      'no-constant-condition': 1,
      'no-case-declarations': 0,
      'no-control-regex': 1,
      'no-debugger': 2,
      'no-dupe-args': 2,
      'no-dupe-keys': 2,
      'no-duplicate-case': 1,
      'no-empty-character-class': 1,
      'no-empty': 2,
      'no-ex-assign': 2,
      'no-func-assign': 1,
      'no-invalid-regexp': 2,
      'no-irregular-whitespace': 1,
      // renamed: no-negated-in-lhs -> no-unsafe-negation
      'no-unsafe-negation': 1,
      'no-obj-calls': 1,
      'no-regex-spaces': 1,
      'no-sparse-arrays': 1,
      'no-unreachable': 1,
      'use-isnan': 2,
      'valid-typeof': 1,
      'no-unexpected-multiline': 1,
      'consistent-return': 1,
      'curly': [1, 'all'],
      'eqeqeq': [2, 'smart'],
      'no-alert': 1,
      'no-caller': 2,
      'no-else-return': 1,
      'no-eval': 2,
      'no-extend-native': 1,
      'no-extra-bind': 1,
      'no-fallthrough': 1,
      'no-implicit-coercion': 2,
      'no-implied-eval': 2,
      'no-iterator': 1,
      'no-lone-blocks': 1,
      'no-loop-func': 1,
      // renamed: no-native-reassign -> no-global-assign
      'no-global-assign': 1,
      'no-new-wrappers': 1,
      'no-octal-escape': 1,
      'no-process-env': 0,
      'no-proto': 1,
      'no-redeclare': 1,
      'no-return-assign': [2, 'except-parens'],
      'no-script-url': 1,
      'no-self-compare': 1,
      'no-sequences': 2,
      'no-throw-literal': 2,
      'no-unused-expressions': 1,
      'no-useless-call': 1,
      'no-void': 2,
      'yoda': 1,
      'strict': [1, 'never'],
      'no-delete-var': 1,
      'no-label-var': 1,
      'no-undef': 1,
      'no-undefined': 1,
      // The legacy config relied on ESLint 8's default caughtErrors: 'none'
      // (caught error params were not checked); ESLint 9+ defaults to 'all'.
      'no-unused-vars': [1, { caughtErrors: 'none' }],
      'camelcase': [2, { properties: 'always' }],
      'new-cap': [2, { newIsCap: true, capIsNew: true }],
      'no-array-constructor': 1,
      'no-lonely-if': 1,
      'no-nested-ternary': 1,
      'no-unneeded-ternary': 1,
      'constructor-super': 1,
      'no-const-assign': 2,
      'no-this-before-super': 2,
      'no-var': 1,
      'prefer-const': 1,
      'prefer-spread': 1,
      'require-yield': 1,
    },
  },
];
