window.esdocSearchIndex = [
  [
    "minidrone-js/src/commandparser.js~commandparser",
    "class/src/CommandParser.js~CommandParser.html",
    "<span>CommandParser</span> <span class=\"search-result-import-path\">minidrone-js/src/CommandParser.js</span>",
    "class"
  ],
  [
    "minidrone-js/src/dronecommand.js~dronecommand",
    "class/src/DroneCommand.js~DroneCommand.html",
    "<span>DroneCommand</span> <span class=\"search-result-import-path\">minidrone-js/src/DroneCommand.js</span>",
    "class"
  ],
  [
    "minidrone-js/src/dronecommandargument.js~dronecommandargument",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html",
    "<span>DroneCommandArgument</span> <span class=\"search-result-import-path\">minidrone-js/src/DroneCommandArgument.js</span>",
    "class"
  ],
  [
    "minidrone-js/src/droneconnection.js~droneconnection",
    "class/src/DroneConnection.js~DroneConnection.html",
    "<span>DroneConnection</span> <span class=\"search-result-import-path\">minidrone-js/src/DroneConnection.js</span>",
    "class"
  ],
  [
    "minidrone-js/src/util/enum.js~enum",
    "class/src/util/Enum.js~Enum.html",
    "<span>Enum</span> <span class=\"search-result-import-path\">minidrone-js/src/util/Enum.js</span>",
    "class"
  ],
  [
    "minidrone-js/src/invalidcommanderror.js~invalidcommanderror",
    "class/src/InvalidCommandError.js~InvalidCommandError.html",
    "<span>InvalidCommandError</span> <span class=\"search-result-import-path\">minidrone-js/src/InvalidCommandError.js</span>",
    "class"
  ],
  [
    "minidrone-js/src/util/reflection.js~gettypename",
    "function/index.html#static-function-getTypeName",
    "<span>getTypeName</span> <span class=\"search-result-import-path\">minidrone-js/src/util/reflection.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/commandparser.js",
    "file/src/CommandParser.js.html",
    "src/CommandParser.js",
    "file"
  ],
  [
    "src/commandparser.js~commandparser#_assertelementexists",
    "class/src/CommandParser.js~CommandParser.html#instance-method-_assertElementExists",
    "src/CommandParser.js~CommandParser#_assertElementExists",
    "method"
  ],
  [
    "src/commandparser.js~commandparser#_commandcache",
    "class/src/CommandParser.js~CommandParser.html#instance-member-_commandCache",
    "src/CommandParser.js~CommandParser#_commandCache",
    "member"
  ],
  [
    "src/commandparser.js~commandparser#_getcommandfrombuffer",
    "class/src/CommandParser.js~CommandParser.html#instance-method-_getCommandFromBuffer",
    "src/CommandParser.js~CommandParser#_getCommandFromBuffer",
    "method"
  ],
  [
    "src/commandparser.js~commandparser#_getjson",
    "class/src/CommandParser.js~CommandParser.html#instance-method-_getJson",
    "src/CommandParser.js~CommandParser#_getJson",
    "method"
  ],
  [
    "src/commandparser.js~commandparser#_getxml",
    "class/src/CommandParser.js~CommandParser.html#instance-method-_getXml",
    "src/CommandParser.js~CommandParser#_getXml",
    "method"
  ],
  [
    "src/commandparser.js~commandparser#constructor",
    "class/src/CommandParser.js~CommandParser.html#instance-constructor-constructor",
    "src/CommandParser.js~CommandParser#constructor",
    "method"
  ],
  [
    "src/commandparser.js~commandparser#getcommand",
    "class/src/CommandParser.js~CommandParser.html#instance-method-getCommand",
    "src/CommandParser.js~CommandParser#getCommand",
    "method"
  ],
  [
    "src/commandparser.js~commandparser#parsebuffer",
    "class/src/CommandParser.js~CommandParser.html#instance-method-parseBuffer",
    "src/CommandParser.js~CommandParser#parseBuffer",
    "method"
  ],
  [
    "src/commandparser.js~commandparser#warmup",
    "class/src/CommandParser.js~CommandParser.html#instance-method-warmup",
    "src/CommandParser.js~CommandParser#warmup",
    "method"
  ],
  [
    "src/commandparser.js~commandparser.__arsdkpath",
    "class/src/CommandParser.js~CommandParser.html#static-member-__arsdkPath",
    "src/CommandParser.js~CommandParser.__arsdkPath",
    "member"
  ],
  [
    "src/commandparser.js~commandparser.__files",
    "class/src/CommandParser.js~CommandParser.html#static-member-__files",
    "src/CommandParser.js~CommandParser.__files",
    "member"
  ],
  [
    "src/commandparser.js~commandparser._arsdkxmlpath",
    "class/src/CommandParser.js~CommandParser.html#static-get-_arsdkXmlPath",
    "src/CommandParser.js~CommandParser._arsdkXmlPath",
    "member"
  ],
  [
    "src/commandparser.js~commandparser._files",
    "class/src/CommandParser.js~CommandParser.html#static-get-_files",
    "src/CommandParser.js~CommandParser._files",
    "member"
  ],
  [
    "src/dronecommand.js",
    "file/src/DroneCommand.js.html",
    "src/DroneCommand.js",
    "file"
  ],
  [
    "src/dronecommand.js~dronecommand#_arguments",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_arguments",
    "src/DroneCommand.js~DroneCommand#_arguments",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#_buffer",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_buffer",
    "src/DroneCommand.js~DroneCommand#_buffer",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#_class",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_class",
    "src/DroneCommand.js~DroneCommand#_class",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#_classid",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_classId",
    "src/DroneCommand.js~DroneCommand#_classId",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#_classname",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_className",
    "src/DroneCommand.js~DroneCommand#_className",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#_command",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_command",
    "src/DroneCommand.js~DroneCommand#_command",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#_commandid",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_commandId",
    "src/DroneCommand.js~DroneCommand#_commandId",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#_commandname",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_commandName",
    "src/DroneCommand.js~DroneCommand#_commandName",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#_deprecated",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_deprecated",
    "src/DroneCommand.js~DroneCommand#_deprecated",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#_description",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_description",
    "src/DroneCommand.js~DroneCommand#_description",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#_maparguments",
    "class/src/DroneCommand.js~DroneCommand.html#instance-method-_mapArguments",
    "src/DroneCommand.js~DroneCommand#_mapArguments",
    "method"
  ],
  [
    "src/dronecommand.js~dronecommand#_project",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_project",
    "src/DroneCommand.js~DroneCommand#_project",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#_projectid",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_projectId",
    "src/DroneCommand.js~DroneCommand#_projectId",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#_projectname",
    "class/src/DroneCommand.js~DroneCommand.html#instance-member-_projectName",
    "src/DroneCommand.js~DroneCommand#_projectName",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#argumentnames",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-argumentNames",
    "src/DroneCommand.js~DroneCommand#argumentNames",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#arguments",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-arguments",
    "src/DroneCommand.js~DroneCommand#arguments",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#bufferflag",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-bufferFlag",
    "src/DroneCommand.js~DroneCommand#bufferFlag",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#buffertype",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-bufferType",
    "src/DroneCommand.js~DroneCommand#bufferType",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#classid",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-classId",
    "src/DroneCommand.js~DroneCommand#classId",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#classname",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-className",
    "src/DroneCommand.js~DroneCommand#className",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#clone",
    "class/src/DroneCommand.js~DroneCommand.html#instance-method-clone",
    "src/DroneCommand.js~DroneCommand#clone",
    "method"
  ],
  [
    "src/dronecommand.js~dronecommand#commandid",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-commandId",
    "src/DroneCommand.js~DroneCommand#commandId",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#commandname",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-commandName",
    "src/DroneCommand.js~DroneCommand#commandName",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#constructor",
    "class/src/DroneCommand.js~DroneCommand.html#instance-constructor-constructor",
    "src/DroneCommand.js~DroneCommand#constructor",
    "method"
  ],
  [
    "src/dronecommand.js~dronecommand#deprecated",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-deprecated",
    "src/DroneCommand.js~DroneCommand#deprecated",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#description",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-description",
    "src/DroneCommand.js~DroneCommand#description",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#gettoken",
    "class/src/DroneCommand.js~DroneCommand.html#instance-method-getToken",
    "src/DroneCommand.js~DroneCommand#getToken",
    "method"
  ],
  [
    "src/dronecommand.js~dronecommand#hasargument",
    "class/src/DroneCommand.js~DroneCommand.html#instance-method-hasArgument",
    "src/DroneCommand.js~DroneCommand#hasArgument",
    "method"
  ],
  [
    "src/dronecommand.js~dronecommand#hasarguments",
    "class/src/DroneCommand.js~DroneCommand.html#instance-method-hasArguments",
    "src/DroneCommand.js~DroneCommand#hasArguments",
    "method"
  ],
  [
    "src/dronecommand.js~dronecommand#projectid",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-projectId",
    "src/DroneCommand.js~DroneCommand#projectId",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#projectname",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-projectName",
    "src/DroneCommand.js~DroneCommand#projectName",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#sendcharacteristicuuid",
    "class/src/DroneCommand.js~DroneCommand.html#instance-get-sendCharacteristicUuid",
    "src/DroneCommand.js~DroneCommand#sendCharacteristicUuid",
    "member"
  ],
  [
    "src/dronecommand.js~dronecommand#tobuffer",
    "class/src/DroneCommand.js~DroneCommand.html#instance-method-toBuffer",
    "src/DroneCommand.js~DroneCommand#toBuffer",
    "method"
  ],
  [
    "src/dronecommand.js~dronecommand#tostring",
    "class/src/DroneCommand.js~DroneCommand.html#instance-method-toString",
    "src/DroneCommand.js~DroneCommand#toString",
    "method"
  ],
  [
    "src/dronecommandargument.js",
    "file/src/DroneCommandArgument.js.html",
    "src/DroneCommandArgument.js",
    "file"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#_description",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-member-_description",
    "src/DroneCommandArgument.js~DroneCommandArgument#_description",
    "member"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#_enum",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-member-_enum",
    "src/DroneCommandArgument.js~DroneCommandArgument#_enum",
    "member"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#_name",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-member-_name",
    "src/DroneCommandArgument.js~DroneCommandArgument#_name",
    "member"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#_parsevalue",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-method-_parseValue",
    "src/DroneCommandArgument.js~DroneCommandArgument#_parseValue",
    "method"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#_type",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-member-_type",
    "src/DroneCommandArgument.js~DroneCommandArgument#_type",
    "member"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#_value",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-member-_value",
    "src/DroneCommandArgument.js~DroneCommandArgument#_value",
    "member"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#constructor",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-constructor-constructor",
    "src/DroneCommandArgument.js~DroneCommandArgument#constructor",
    "method"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#description",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-get-description",
    "src/DroneCommandArgument.js~DroneCommandArgument#description",
    "member"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#getvaluesize",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-method-getValueSize",
    "src/DroneCommandArgument.js~DroneCommandArgument#getValueSize",
    "method"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#hasenumproperty",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-get-hasEnumProperty",
    "src/DroneCommandArgument.js~DroneCommandArgument#hasEnumProperty",
    "member"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#name",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-get-name",
    "src/DroneCommandArgument.js~DroneCommandArgument#name",
    "member"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#tostring",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-method-toString",
    "src/DroneCommandArgument.js~DroneCommandArgument#toString",
    "method"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#type",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-get-type",
    "src/DroneCommandArgument.js~DroneCommandArgument#type",
    "member"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#value",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-get-value",
    "src/DroneCommandArgument.js~DroneCommandArgument#value",
    "member"
  ],
  [
    "src/dronecommandargument.js~dronecommandargument#value",
    "class/src/DroneCommandArgument.js~DroneCommandArgument.html#instance-set-value",
    "src/DroneCommandArgument.js~DroneCommandArgument#value",
    "member"
  ],
  [
    "src/droneconnection.js",
    "file/src/DroneConnection.js.html",
    "src/DroneConnection.js",
    "file"
  ],
  [
    "src/droneconnection.js~droneconnection#_characteristiclookupcache",
    "class/src/DroneConnection.js~DroneConnection.html#instance-member-_characteristicLookupCache",
    "src/DroneConnection.js~DroneConnection#_characteristicLookupCache",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#_commandcallback",
    "class/src/DroneConnection.js~DroneConnection.html#instance-member-_commandCallback",
    "src/DroneConnection.js~DroneConnection#_commandCallback",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#_getstep",
    "class/src/DroneConnection.js~DroneConnection.html#instance-method-_getStep",
    "src/DroneConnection.js~DroneConnection#_getStep",
    "method"
  ],
  [
    "src/droneconnection.js~droneconnection#_handleincoming",
    "class/src/DroneConnection.js~DroneConnection.html#instance-method-_handleIncoming",
    "src/DroneConnection.js~DroneConnection#_handleIncoming",
    "method"
  ],
  [
    "src/droneconnection.js~droneconnection#_onnoblestatechange",
    "class/src/DroneConnection.js~DroneConnection.html#instance-method-_onNobleStateChange",
    "src/DroneConnection.js~DroneConnection#_onNobleStateChange",
    "method"
  ],
  [
    "src/droneconnection.js~droneconnection#_onperipheraldiscovery",
    "class/src/DroneConnection.js~DroneConnection.html#instance-method-_onPeripheralDiscovery",
    "src/DroneConnection.js~DroneConnection#_onPeripheralDiscovery",
    "method"
  ],
  [
    "src/droneconnection.js~droneconnection#_peripheral",
    "class/src/DroneConnection.js~DroneConnection.html#instance-member-_peripheral",
    "src/DroneConnection.js~DroneConnection#_peripheral",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#_sensorstore",
    "class/src/DroneConnection.js~DroneConnection.html#instance-member-_sensorStore",
    "src/DroneConnection.js~DroneConnection#_sensorStore",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#_setupperipheral",
    "class/src/DroneConnection.js~DroneConnection.html#instance-method-_setupPeripheral",
    "src/DroneConnection.js~DroneConnection#_setupPeripheral",
    "method"
  ],
  [
    "src/droneconnection.js~droneconnection#_stepstore",
    "class/src/DroneConnection.js~DroneConnection.html#instance-member-_stepStore",
    "src/DroneConnection.js~DroneConnection#_stepStore",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#_updatesensors",
    "class/src/DroneConnection.js~DroneConnection.html#instance-method-_updateSensors",
    "src/DroneConnection.js~DroneConnection#_updateSensors",
    "method"
  ],
  [
    "src/droneconnection.js~droneconnection#_validateperipheral",
    "class/src/DroneConnection.js~DroneConnection.html#instance-method-_validatePeripheral",
    "src/DroneConnection.js~DroneConnection#_validatePeripheral",
    "method"
  ],
  [
    "src/droneconnection.js~droneconnection#characteristics",
    "class/src/DroneConnection.js~DroneConnection.html#instance-member-characteristics",
    "src/DroneConnection.js~DroneConnection#characteristics",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#connected",
    "class/src/DroneConnection.js~DroneConnection.html#instance-get-connected",
    "src/DroneConnection.js~DroneConnection#connected",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#constructor",
    "class/src/DroneConnection.js~DroneConnection.html#instance-constructor-constructor",
    "src/DroneConnection.js~DroneConnection#constructor",
    "method"
  ],
  [
    "src/droneconnection.js~droneconnection#dronefilter",
    "class/src/DroneConnection.js~DroneConnection.html#instance-member-droneFilter",
    "src/DroneConnection.js~DroneConnection#droneFilter",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#getcharacteristic",
    "class/src/DroneConnection.js~DroneConnection.html#instance-method-getCharacteristic",
    "src/DroneConnection.js~DroneConnection#getCharacteristic",
    "method"
  ],
  [
    "src/droneconnection.js~droneconnection#getsensor",
    "class/src/DroneConnection.js~DroneConnection.html#instance-method-getSensor",
    "src/DroneConnection.js~DroneConnection#getSensor",
    "method"
  ],
  [
    "src/droneconnection.js~droneconnection#getsensorfromtoken",
    "class/src/DroneConnection.js~DroneConnection.html#instance-method-getSensorFromToken",
    "src/DroneConnection.js~DroneConnection#getSensorFromToken",
    "method"
  ],
  [
    "src/droneconnection.js~droneconnection#loglevel",
    "class/src/DroneConnection.js~DroneConnection.html#instance-get-logLevel",
    "src/DroneConnection.js~DroneConnection#logLevel",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#loglevel",
    "class/src/DroneConnection.js~DroneConnection.html#instance-set-logLevel",
    "src/DroneConnection.js~DroneConnection#logLevel",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#noble",
    "class/src/DroneConnection.js~DroneConnection.html#instance-member-noble",
    "src/DroneConnection.js~DroneConnection#noble",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#parser",
    "class/src/DroneConnection.js~DroneConnection.html#instance-member-parser",
    "src/DroneConnection.js~DroneConnection#parser",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#peripheral",
    "class/src/DroneConnection.js~DroneConnection.html#instance-get-peripheral",
    "src/DroneConnection.js~DroneConnection#peripheral",
    "member"
  ],
  [
    "src/droneconnection.js~droneconnection#runcommand",
    "class/src/DroneConnection.js~DroneConnection.html#instance-method-runCommand",
    "src/DroneConnection.js~DroneConnection#runCommand",
    "method"
  ],
  [
    "src/invalidcommanderror.js",
    "file/src/InvalidCommandError.js.html",
    "src/InvalidCommandError.js",
    "file"
  ],
  [
    "src/invalidcommanderror.js~invalidcommanderror#constructor",
    "class/src/InvalidCommandError.js~InvalidCommandError.html#instance-constructor-constructor",
    "src/InvalidCommandError.js~InvalidCommandError#constructor",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/util/enum.js",
    "file/src/util/Enum.js.html",
    "src/util/Enum.js",
    "file"
  ],
  [
    "src/util/enum.js~enum#constructor",
    "class/src/util/Enum.js~Enum.html#instance-constructor-constructor",
    "src/util/Enum.js~Enum#constructor",
    "method"
  ],
  [
    "src/util/enum.js~enum#findforvalue",
    "class/src/util/Enum.js~Enum.html#instance-method-findForValue",
    "src/util/Enum.js~Enum#findForValue",
    "method"
  ],
  [
    "src/util/enum.js~enum#haskey",
    "class/src/util/Enum.js~Enum.html#instance-method-hasKey",
    "src/util/Enum.js~Enum#hasKey",
    "method"
  ],
  [
    "src/util/enum.js~enum#hasvalue",
    "class/src/util/Enum.js~Enum.html#instance-method-hasValue",
    "src/util/Enum.js~Enum#hasValue",
    "method"
  ],
  [
    "src/util/enum.js~enum#keys",
    "class/src/util/Enum.js~Enum.html#instance-method-keys",
    "src/util/Enum.js~Enum#keys",
    "method"
  ],
  [
    "src/util/enum.js~enum#tostring",
    "class/src/util/Enum.js~Enum.html#instance-method-toString",
    "src/util/Enum.js~Enum#toString",
    "method"
  ],
  [
    "src/util/enum.js~enum#values",
    "class/src/util/Enum.js~Enum.html#instance-method-values",
    "src/util/Enum.js~Enum#values",
    "method"
  ],
  [
    "src/util/enum.js~enum._iota",
    "class/src/util/Enum.js~Enum.html#static-get-_iota",
    "src/util/Enum.js~Enum._iota",
    "member"
  ],
  [
    "src/util/reflection.js",
    "file/src/util/reflection.js.html",
    "src/util/reflection.js",
    "file"
  ]
]